//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_car_demo2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.order_items = new HashSet<order_items>();
        }
    
        public int product_id { get; set; }
        [Required (ErrorMessage = "Vui lòng nhập tên sản phẩm"), MaxLength(225, ErrorMessage = "Không nhập quá 225 kí tự"), DisplayName("Tên Sản Phẩm")]
        public string product_name { get; set; }
        public int brand_id { get; set; }
        public int category_id { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập năm sản xuất"), Range(1500,2999, ErrorMessage = " Vui lòng nhập trong khoảng 1500-2999"), DisplayName("Năm sản xuất")]
        public Nullable<short> model_year { get; set; }
        [DisplayName("Hình ảnh")]
        public string images { get; set; }
        [DisplayName("Giá"), DisplayFormat(DataFormatString = "{0:0,0}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> price { get; set; }
        [DisplayName("Mô tả")]
        public string desciption { get; set; }
    
        public virtual brand brand { get; set; }
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_items> order_items { get; set; }
        public virtual stock stock { get; set; }
    }
}
