//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_car_demo2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class stock
    {
        public int product_id { get; set; }
        [DisplayName("Số Lượng")]
        public Nullable<int> quantity { get; set; }
    
        public virtual product product { get; set; }
    }
}
